# Generated by Django 5.0.3 on 2024-08-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_pan_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pan_card',
        ),
    ]
