# Generated by Django 5.0.3 on 2024-08-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_pan_card'),
        ('accounts', '0004_customuser_pan_card'),
    ]

    operations = [
    ]
