# Generated by Django 5.0.3 on 2024-08-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20240825_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pan_card',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
