# Generated by Django 5.0.3 on 2024-08-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_pan_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_add_product', 'Can add product'), ('can_edit_product', 'Can edit product'), ('can_deliver_product', 'Can deliver product')]},
        ),
    ]
