# Generated by Django 5.0.3 on 2024-09-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_deliveryboy_pan_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_delivery_boy',
            field=models.BooleanField(default=True),
        ),
    ]
