# Generated by Django 5.0.3 on 2024-09-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_deliveryboy_is_delivery_boy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='is_delivery_boy',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_delivery_boy',
            field=models.BooleanField(default=False),
        ),
    ]
