# Generated by Django 5.0.3 on 2024-09-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_deliveryboy_is_delivery_boy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryboy',
            old_name='Pan_card',
            new_name='additional_pan_card',
        ),
    ]
