# Generated by Django 5.0.3 on 2024-09-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_pan_card_deliveryboy_additional_pan_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryboy',
            old_name='additional_pan_card',
            new_name='Pan_card',
        ),
    ]
