# Generated by Django 5.0.3 on 2024-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_deliveryboy_pan_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
