# Generated by Django 5.0.3 on 2024-09-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
