# Generated by Django 5.0.3 on 2024-09-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_order_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
