# Generated by Django 5.0.3 on 2024-09-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_order_delivery_boy_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_boy',
        ),
    ]
