# Generated by Django 5.0.3 on 2024-09-17 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_remove_order_delivery_boy'),
        ('accounts', '0015_deliveryboy_is_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.deliveryboy'),
        ),
    ]
