# Generated by Django 5.0.3 on 2024-09-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_order_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_in_transit',
            field=models.BooleanField(default=False),
        ),
    ]
